import Link from "next/link";
import { ArrowUpRight, BrainCircuit, CheckCircle2, ClipboardList, Factory, PackageCheck, ShieldCheck, Wrench } from "lucide-react";

const modules = [
  { title: "Ventas", detail: "Convierte una necesidad industrial en una oferta trazable, aprobada y lista para operar.", jobs: ["Prospección y CRM", "Ofertas, revisiones y aprobaciones", "Transferencia a Órdenes"], icon: ArrowUpRight },
  { title: "Órdenes", detail: "Coordina la reparación desde recepción, diagnóstico y alcance hasta entrega o garantía.", jobs: ["Intake de activos", "Procesos, tareas y tiempos", "Entrega y trazabilidad"], icon: ClipboardList },
  { title: "Planeación", detail: "Compromete fechas reales y dispara las acciones que cada reparación necesita.", jobs: ["Programación de capacidad", "Diagramas de ejecución", "Disparos a Compras y Calidad"], icon: Factory },
  { title: "Recursos", detail: "Da visibilidad a las personas, habilidades, estaciones y equipos críticos de operación.", jobs: ["Disponibilidad técnica", "Matriz de habilidades", "Uso de equipos clave"], icon: Wrench },
  { title: "Almacén y Compras", detail: "Conecta requerimientos de una orden con inventario, proveedor, recepción y costo real.", jobs: ["Reservas y consumos", "Requisiciones y órdenes de compra", "Recepción y trazabilidad"], icon: PackageCheck },
  { title: "Quality Engine", detail: "Convierte estándares propios en pruebas repetibles con evidencia y liberación técnica.", jobs: ["Plantillas y mediciones", "Evidencia visual y documental", "Liberación, re-trabajo y auditoría"], icon: ShieldCheck },
  { title: "Ingeniería", detail: "Centraliza especificaciones, planos, notas y versiones que hacen reproducible la reparación.", jobs: ["Documentación técnica", "Versiones y aprobaciones", "Contexto para Órdenes y Calidad"], icon: BrainCircuit },
  { title: "Agente IA", detail: "Consulta la memoria operativa autorizada y responde con fuentes, no con suposiciones.", jobs: ["Búsqueda semántica citada", "Análisis de pruebas", "Asistencia para decisiones"], icon: BrainCircuit },
];

export default function ProductPage() {
  return <main className="product-page"><nav className="product-nav"><Link className="product-brand" href="/app"><span />protek</Link><div><Link href="#modulos">Módulos</Link><Link href="#flujo">Flujo operativo</Link><Link className="product-nav-cta" href="/app">Abrir demo <ArrowUpRight size={15} /></Link></div></nav><section className="product-hero"><p>PROTEK INDUSTRIAL / PRODUCTO</p><h1>Un sistema de trabajo para cada reparación que importa.</h1><div className="product-hero-bottom"><p>Protek conecta la decisión comercial, la ejecución técnica, el abastecimiento y la liberación de calidad en un mismo hilo operativo.</p><Link className="product-primary-cta" href="/app">Explorar la demo <ArrowUpRight size={17} /></Link></div></section><section className="product-flow" id="flujo"><div><span>01</span><h2>Oferta</h2><p>La necesidad se vuelve alcance, costo, responsable y compromiso.</p></div><div><span>02</span><h2>Orden</h2><p>El trabajo se planifica, se asigna y se ejecuta con evidencia.</p></div><div><span>03</span><h2>Liberación</h2><p>Calidad valida el resultado antes de entregar o facturar.</p></div><div><span>04</span><h2>Memoria</h2><p>La reparación alimenta el siguiente diagnóstico y decisión.</p></div></section><section className="product-modules" id="modulos"><header><p>ARQUITECTURA DE PRODUCTO</p><h2>Un módulo para cada responsabilidad. Un solo contexto para todos.</h2></header><div className="product-module-grid">{modules.map((module, index) => { const Icon = module.icon; return <article key={module.title} className={index === 5 ? "is-featured" : ""}><div><Icon size={20} /><span>{String(index + 1).padStart(2, "0")}</span></div><h3>{module.title}</h3><p>{module.detail}</p><ul>{module.jobs.map((job) => <li key={job}><CheckCircle2 size={14} />{job}</li>)}</ul></article>; })}</div></section><section className="product-close"><p>La operación industrial no necesita más hojas de cálculo. Necesita un sistema que recuerde, conecte y haga avanzar el trabajo.</p><Link className="product-primary-cta" href="/app">Abrir Protek <ArrowUpRight size={17} /></Link></section></main>;
}
